/* tslint:disable */
import { GraphQLResolveInfo } from 'graphql';
/**
 * This file is auto-generated by graphql-schema-typescript
 * Please note that any changes in this file may be overwritten
 */
 

/*******************************
 *                             *
 *          TYPE DEFS          *
 *                             *
 *******************************/
export interface Query {
  user?: User;
  conversation?: Conversation;
}

export interface User {
  id: string;
  username: string;
  publicKey: string;
}

export interface Conversation {
  id: string;
  from: string;
  to: string;
  messages?: Array<Message | null>;
}

export interface Message {
  body: string;
  author: User;
  timestamp: string;
}

export interface Mutation {
  createUser: User;
  createConversation: Conversation;
  sendMessage: boolean;
}

export interface CreateUserInput {
  username: string;
  publicKey: string;
}

export interface CreateConversationInput {
  from: string;
  to: string;
}

export interface SendMessageInput {
  authorId: string;
  conversationId: string;
  body: string;
}

/*********************************
 *                               *
 *         TYPE RESOLVERS        *
 *                               *
 *********************************/
/**
 * This interface define the shape of your resolver
 * Note that this type is designed to be compatible with graphql-tools resolvers
 * However, you can still use other generated interfaces to make your resolver type-safed
 */
export interface Resolver {
  Query?: QueryTypeResolver;
  User?: UserTypeResolver;
  Conversation?: ConversationTypeResolver;
  Message?: MessageTypeResolver;
  Mutation?: MutationTypeResolver;
}
export interface QueryTypeResolver<TParent = any> {
  user?: QueryToUserResolver<TParent>;
  conversation?: QueryToConversationResolver<TParent>;
}

export interface QueryToUserResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface QueryToConversationResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserTypeResolver<TParent = any> {
  id?: UserToIdResolver<TParent>;
  username?: UserToUsernameResolver<TParent>;
  publicKey?: UserToPublicKeyResolver<TParent>;
}

export interface UserToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserToUsernameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserToPublicKeyResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ConversationTypeResolver<TParent = any> {
  id?: ConversationToIdResolver<TParent>;
  from?: ConversationToFromResolver<TParent>;
  to?: ConversationToToResolver<TParent>;
  messages?: ConversationToMessagesResolver<TParent>;
}

export interface ConversationToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ConversationToFromResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ConversationToToResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ConversationToMessagesResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MessageTypeResolver<TParent = any> {
  body?: MessageToBodyResolver<TParent>;
  author?: MessageToAuthorResolver<TParent>;
  timestamp?: MessageToTimestampResolver<TParent>;
}

export interface MessageToBodyResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MessageToAuthorResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MessageToTimestampResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MutationTypeResolver<TParent = any> {
  createUser?: MutationToCreateUserResolver<TParent>;
  createConversation?: MutationToCreateConversationResolver<TParent>;
  sendMessage?: MutationToSendMessageResolver<TParent>;
}

export interface MutationToCreateUserArgs {
  input: CreateUserInput;
}
export interface MutationToCreateUserResolver<TParent = any, TResult = any> {
  (parent: TParent, args: MutationToCreateUserArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MutationToCreateConversationArgs {
  input: CreateConversationInput;
}
export interface MutationToCreateConversationResolver<TParent = any, TResult = any> {
  (parent: TParent, args: MutationToCreateConversationArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MutationToSendMessageArgs {
  input: SendMessageInput;
}
export interface MutationToSendMessageResolver<TParent = any, TResult = any> {
  (parent: TParent, args: MutationToSendMessageArgs, context: any, info: GraphQLResolveInfo): TResult;
}
